// Generated by CoffeeScript 1.6.2
(function() {
  var Gpx, processWaypoint, xpath;

  xpath = require('xpath');

  processWaypoint = function(wpt) {
    var data;

    data = {
      lat: parseFloat(xpath.select("@lat", wpt)[0].value),
      lon: parseFloat(xpath.select("@lon", wpt)[0].value),
      ele: parseFloat(xpath.select("ele/text()", wpt).toString()),
      desc: xpath.select("desc/text()", wpt).toString()
    };
    return data;
  };

  Gpx = (function() {
    function Gpx(dom) {
      this.dom = dom;
      if (this.dom == null) {
        throw "An XML document is required";
      }
    }

    Gpx.prototype.toJson = function() {
      var wpt, _i, _len, _ref, _results;

      _ref = xpath.select("//wpt", this.dom);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        wpt = _ref[_i];
        _results.push(processWaypoint(wpt));
      }
      return _results;
    };

    return Gpx;

  })();

  module.exports = function(dom) {
    return new Gpx(dom);
  };

}).call(this);
