// Generated by CoffeeScript 1.6.2
(function() {
  var Gpx, latlon, processPoint, xpath;

  xpath = require('xpath');

  latlon = require('./latlon');

  processPoint = function(wpt) {
    var coord, desc, ele, lat, lon;

    lat = parseFloat(xpath.select("@lat", wpt)[0].value);
    lon = parseFloat(xpath.select("@lon", wpt)[0].value);
    ele = parseFloat(xpath.select("ele/text()", wpt).toString());
    desc = xpath.select("desc/text()", wpt).toString();
    coord = new latlon(lat, lon, ele);
    coord.desc = desc;
    return coord;
  };

  Gpx = (function() {
    function Gpx(dom) {
      this.dom = dom;
      if (this.dom == null) {
        throw "An XML document is required";
      }
    }

    Gpx.prototype.toJson = function() {
      var wpt, _i, _len, _ref, _results;

      _ref = xpath.select("//wpt|//trkpt", this.dom);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        wpt = _ref[_i];
        _results.push(processPoint(wpt));
      }
      return _results;
    };

    return Gpx;

  })();

  module.exports = function(dom) {
    return new Gpx(dom);
  };

}).call(this);
