// Generated by CoffeeScript 1.6.2
(function() {
  var Trail, When, createTrail, defaultLoadOptions, fs, gpx, gpxToJson, parseIntoDom, readFile, xmlParser, _;

  When = require("when");

  _ = require("underscore");

  fs = require('fs');

  xmlParser = require("xmldom").DOMParser;

  gpx = require("./gpx");

  readFile = function(fileName) {
    var hasReadFile;

    hasReadFile = When.defer();
    fs.readFile(fileName, 'utf8', function(err, contents) {
      if (err != null) {
        return hasReadFile.reject(err);
      }
      return hasReadFile.resolve(contents);
    });
    return hasReadFile.promise;
  };

  Trail = (function() {
    function Trail(path) {
      this.path = path;
    }

    return Trail;

  })();

  defaultLoadOptions = {};

  parseIntoDom = function(xml) {
    return new xmlParser().parseFromString(xml);
  };

  gpxToJson = function(dom) {
    return gpx(dom).toJson();
  };

  createTrail = function(data) {
    var path;

    path = data[0];
    return new Trail(path);
  };

  module.exports.load = function(options) {
    var path;

    options = _.extend({}, defaultLoadOptions, options);
    if (options.path == null) {
      throw "A trail \"path\" is required";
    }
    path = readFile(options.path, 'utf8').then(parseIntoDom).then(gpxToJson);
    return When.join(path).then(createTrail);
  };

}).call(this);
